### ISSUE TITLE
major review and structure of ontologies

### ISSUE THREAD

**Issue by BrodeurJS** [ISO-TC211/def-isotc211.github.io#4]
Ontologies have been updated on ISO-TC211/GOM/isotc211_GOM_harmonizedOntology/ with the correct hierarchical structure. As convenor of GOM, what is the correct process to move this on http://def.isotc211.org.
Thanks,

**Comment by ronaldtse** [comment]
Hello @BrodeurJS , it's very easy -- ontologies on def.isotc211.org are managed in the other git repository (https://github.com/ISO-TC211/ontologies).

Steps:
1. Copy over the files from ISO-TC211/GOM/isotc211_GOM_harmonizedOntology/ over to ISO-TC211/ontologies.
2. Commit and push the changes
3. Go to the continuous integration site (https://travis-ci.com/ISO-TC211/def.isotc211.org) and click "Restart build" 
<img width="695" alt="Screen Shot 2019-05-17 at 1 20 31 PM" src="https://user-images.githubusercontent.com/11865/57904706-8d2dbd00-78a6-11e9-8c61-fce78560888e.png">

4. The site will be updated!

**Comment by BrodeurJS** [comment]
Thanks @ronaldtse, looks like I succeed!
Then the main page for ontology (https://def.isotc211.org/) need to be updated.
How to do it? Can I do it?

**Comment by ronaldtse** [comment]
Sorry for the late reply!

To bring the ontologies onto def.isotc211.org, you would usually:

1. Go to https://travis-ci.com/ISO-TC211/def.isotc211.org

2. Click on the "More Options" menu, then click on the "Trigger Build" button:

<img width="566" alt="Screen Shot 2019-05-24 at 11 20 03 AM" src="https://user-images.githubusercontent.com/11865/58300653-05036680-7e16-11e9-9a69-0454289ce07e.png">

3. Click on "Trigger custom build" in the popup:

<img width="436" alt="Screen Shot 2019-05-24 at 11 20 26 AM" src="https://user-images.githubusercontent.com/11865/58300677-19476380-7e16-11e9-9629-b4209de85664.png">


However, in this case, the update has already been deployed due to further changes we made after (as you can see the build has been run due to other updates), so there's nothing to be done in this case.

You could always try clicking on this button to trigger a build -- there are no side effects!

**Comment by BrodeurJS** [comment]
Hi Ron!

I am trying today (2019-11-14) to publish new ontologies on 
def.isotc211.org. The new ontologies have been moved to 
https://github.com/ISO-TC211/ontologies sucessfully (iso19111/2019 and 
iso19112/2019. However when I lunched the build command (either via 
"Restart Build" or "Trigger Build") , I got first try #24 errored and 
second #25 errored. Possibly, I did something wrong... could you please 
let me know what and what to do to published the new ontologies sucessfully!

Regards,

Jean,



Le 2019-05-23 à 23:22, Ronald Tse a écrit :

**Comment by ronaldtse** [comment]
Hi @BrodeurJS ! Our messages just crossed (I emailed you)

I thought you might have run the Travis build. Apologies for not letting you know in advance, but we’ve recently switched from Travis CI to GitHub Actions for deployment. The reason for the switch was that GHA is much faster in running jobs.

What this mean is that the current build page is located here:
https://github.com/ISO-TC211/def.isotc211.org/actions

<img width="1098" alt="Screen Shot 2019-11-15 at 12 28 45 AM" src="https://user-images.githubusercontent.com/11865/68877698-724ae100-0741-11ea-8115-c0071ea61fc8.png">


If you’d like to build the `master` branch, the current method is to make a push to the def.isotc211.org repo. Unlike what we had before at Travis, there is currently no method to “manually trigger” a deployment yet (https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/m-p/31517#M813)..

As of now, the latest deployment has already been run so the ontologies should have been deployed.

Let me know if you need any further help. Thanks!

**Comment by BrodeurJS** [comment]
I don't know why but now browsing the ontologies I can see the new ones added!
Something that I don't understand worked magically!
Jean,

**Comment by BrodeurJS** [comment]
There are three different actions available. You launched the 
deploy-master action. So I understand that this is the one I should use 
in future deployments?


Le 2019-11-14 à 11:47, Ronald Tse a écrit :

**Comment by ronaldtse** [comment]
@BrodeurJS correct, except that there is no way to manually trigger this. The only way to trigger this action is to make a "git push" to the `master` branch.

In command line it would be this:

```sh
git checkout master
git commit --allow-empty -m "Trigger deploy"
git push
```

Then `deploy-master` will run and deploy!
